### ISSUE TITLE
Following the readme does not work as expected (class not found error)

### ISSUE THREAD

**Issue by Achim63** [fridis/fuzion#3]
How to reproduce:
Follow the readme up to "fz factors"
Run "fz factors" or "fz -c factors"

Result:
"Error: Could not find or load main class dev.flang.tools.Fuzion
Caused by: java.lang.ClassNotFoundException: dev.flang.tools.Fuzion"

Expected result:
No error / addition of missing steps in readme

**Comment by fridis** [comment]
I cannot reproduce the problem, just tried the following commands

 2001  mkdir testfuzion
 2002  cd testfuzion/
 2003  git clone https://github.com/fridis/fuzion
 2004  cd fuzion/
 2005  make
 2006  cd build
 2007  export PATH=$PWD/bin:$PATH
 2008  cd tests/rosettacode_factors_of_an_integer
 2009  fz factors
 2010  fz -c factors
 2011  ./factors

and everything worked as expected. One limitation I found is that the current directory must not have any spaces in the name, make fails in this case. 

If you leave out the 'make' step and ignore the error reported by 'cd build', you get the described error, which IMHO is somewhat deserved. I will try to improve the README.

**Comment by Achim63** [comment]
There were no spaces in any path, so the error must have had a different cause. After trying again, at least I could make fz start up (but get errors because of the TRUE/true and FALSE/false clash on a case insensitive filesystem, see other issue I opened).
