### ISSUE TITLE
fz won't work on case insensitive filesystems

### ISSUE THREAD

**Issue by Achim63** [fridis/fuzion#4]
Cloning the repository, git puts out the following warning:
"warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'lib/FALSE.fz'
  'lib/false.fz'
  'lib/TRUE.fz'
  'lib/true.fz'"

In Ubuntu 20 (wsl2 under Windows), this seems to be the cause for lots of errors trying to run an .fz file ("<built-in>: error 1: Internally referenced feature 'TRUE' not found"). Also unzipping the downloaded .zip gives errors on Windows regarding those files.

So I tried again on OSX, but unfortunately 'make' does not work (b.t.w. none of the used directory paths have any spaces in them, so I'm not sure what went wrong in my first tries). Installed are Apple clang v 12.0 and java version 1.8.0_261. Here's the output:
mkdir -p ./build/classes
javac -d ./build/classes ./src/dev/flang/util/ANY.java ./src/dev/flang/util/Errors.java ./src/dev/flang/util/FuzionOptions.java ./src/dev/flang/util/FuzionConstants.java ./src/dev/flang/util/Intervals.java ./src/dev/flang/util/List.java ./src/dev/flang/util/Map2Int.java ./src/dev/flang/util/MapComparable2Int.java ./src/dev/flang/util/SourceFile.java ./src/dev/flang/util/SourcePosition.java ./src/dev/flang/util/Terminal.java
./src/dev/flang/util/Errors.java:461: error: cannot find symbol
    var legal = new StringBuilder();
    ^
  symbol:   class var
  location: class Errors
./src/dev/flang/util/Errors.java:462: error: cannot find symbol
    var comma = "";
    ^
  symbol:   class var
  location: class Errors
./src/dev/flang/util/Errors.java:463: error: cannot find symbol
    for (var c : escapes)
         ^
  symbol:   class var
  location: class Errors
./src/dev/flang/util/SourceFile.java:107: error: cannot find symbol
  public static Path STDIN = Path.of("-");
                                 ^
  symbol:   method of(String)
  location: interface Path
./src/dev/flang/util/SourceFile.java:114: error: cannot find symbol
  public static Path BUILT_IN = Path.of("--builtin--");
                                    ^
  symbol:   method of(String)
  location: interface Path
./src/dev/flang/util/SourceFile.java:194: error: cannot find symbol
             fileName == STDIN    ? System.in.readAllBytes()
                                             ^
  symbol:   method readAllBytes()
  location: variable in of type InputStream
./src/dev/flang/util/Intervals.java:79: error: cannot find symbol
        for (var v : _map.subMap(min, max).keySet())
             ^
  symbol:   class var
  location: class Intervals<PROPERTY>
  where PROPERTY is a type-variable:
    PROPERTY extends Object declared in class Intervals
./src/dev/flang/util/Map2Int.java:108: error: cannot find symbol
    var res = _mapT2Int.get(t);
    ^
  symbol:   class var
  location: class Map2Int<T>
  where T is a type-variable:
    T extends Object declared in class Map2Int
./src/dev/flang/util/Map2Int.java:128: error: cannot find symbol
    var res = _mapT2Int.get(t);
    ^
  symbol:   class var
  location: class Map2Int<T>
  where T is a type-variable:
    T extends Object declared in class Map2Int
Note: ./src/dev/flang/util/List.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
9 errors
make: *** [build/classes/dev/flang/util/__marker_for_make__] Error 1

**Comment by fridis** [comment]
These are two issues: case-insensitive filesystem (Windows) and javac version (11 is required, currently documented only in the Makefile). 
The case-sensitivity issue will be fixed when the standard types are moved to a global universe.fz (see the comments '# NYI: move to universe.fz' in FALSE.fz and similar files.

**Comment by fridis** [comment]
created new issue #5 for the case sensitivity issue
