### ISSUE TITLE
Add syntactic sugar for defining fractions

### ISSUE THREAD

**Issue by michaellilltokiwa** [fridis/fuzion#48]
It should be possible for fuzion to infer the type here:
```
fraction_test is
  x fraction<i64> := 1
```
Returns this error right now:

    /home/not_synced/flang_dev/content/idioms/examples/idiom67ex.fz:2:3: error 1: Incompatible types in assignment
      x fraction<i64> := 1
    --^
    assignment to field : 'ex67.x'
    expected formal type: 'fraction<i64>'
    actual type found   : 'i32'
    assignable to       : 'i32'
    for value assigned  : '1'

    one error.

**Comment by fridis** [comment]
I am not happy about this, I would like fraction to be a standard library class without any specific support or special handling in the compiler. What would be possible without any additional support is allowing this

```
x := fraction<i64> 1
```
or
```
x := fraction (i64 1)
```
All we would need for this is to add a feature declaration as follows
```
fraction<T: integer<T>>(num T) => num ⁄ num.one
```
