### ISSUE TITLE
Trying to build Fuzion on Windows 10 gives an error - continued

### ISSUE THREAD

**Issue by Ivo-Balbaert** [fridis/fuzion#70]
Thanks for the fix for the previous error.

With make on cmd, I still get 2 errors from javac:

javac -encoding UTF8 -source 16 -cp ./build/classes -d ./build/classes ./src/dev/flang/tools/Fuzion.java ./src/dev/flang/tools/Latex.java ./src/dev/flang/tools/AceMode.java ./src/dev/flang/tools/Pretty.java ./src/dev/flang/tools/Tool.java ./build/generated/src/dev/flang/tools/Version.java
.\build\generated\src\dev\flang\tools\Version.java:49: error: unclosed string literal
  public static final String VERSION = "0.060dev
                                       ^
.\build\generated\src\dev\flang\tools\Version.java:50: error: unclosed string literal
";
^
.\build\generated\src\dev\flang\tools\Version.java:68: error: unclosed string literal
  public static final String BUILTBY = "@DESKTOP-KN14QQK
                                       ^
.\build\generated\src\dev\flang\tools\Version.java:69: error: unclosed string literal
";
^
4 errors
make: *** [Makefile:316: build/classes/dev/flang/tools/__marker_for_make__] Error 1

The file Version.java contains 2 instances of an "unclosed string literal":

public static final String VERSION = "0.060dev
  ";

public static final String BUILTBY = "@DESKTOP-KN14QQK
  ";

Apparently this error only pops up during Java compilation on Windows?

**Comment by michaellilltokiwa** [comment]
Hello @Ivo-Balbaert ,

unfortunately building via powershell/cmd does not work yet.
I'm actually surprised you have come this far. When I try building via cmd it errors out much earlier.

This is how I succeeded building fuzion on windows.

1) Install chocolatey: https://chocolatey.org/install
2) choco install git openjdk make msys2
3) in C:\tools\msys64\msys2_shell.cmd change line: 'rem set MSYS2_PATH_TYPE=inherit' to 'set MSYS2_PATH_TYPE=inherit'
4) execute: C:\tools\msys64\msys2_shell.cmd
5) pacman -S mingw-w64-x86_64-clang
6) make

**Comment by Ivo-Balbaert** [comment]
Thanks for the info! 
When following these steps I had some problems, which persisted even after repeating the procedure:

after step 4: C:/tools/msys64/usr/bin/grep.exe: error while loading shared libraries: msys-pcre-1.dll: cannot open shared object file: No such file or directory

ivoba@DESKTOP-KN14QQK MSYS ~

step 5: $ pacman -S mingw-w64-x86_64-clang
bash: pacman: command not found

Then I followed the installation procedure from https://www.msys2.org/  overwriting everything in c:\tools\msys64. Then steps 4 and 5 ran without any problem.

Then when doing **make** in the MSYS2 shell, I encountered the same problem as mentioned at the start of this issue:

ivoba@DESKTOP-KN14QQK MSYS /c/fuzion
# make
mkdir -p ./build/classes
javac -encoding UTF8 -source 16 -cp ./build/classes -d ./build/classes ./src/dev/flang/tools/Fuzion.java ./src/dev/flang/tools/Latex.java ./src/dev/flang/tools/AceMode.java ./src/dev/flang/tools/Pretty.java ./src/dev/flang/tools/Tool.java ./build/generated/src/dev/flang/tools/Version.java
.\build\generated\src\dev\flang\tools\Version.java:49: error: unclosed string literal
  public static final String VERSION = "0.060dev
                                       ^
.\build\generated\src\dev\flang\tools\Version.java:50: error: unclosed string literal
  ";
  ^
.\build\generated\src\dev\flang\tools\Version.java:68: error: unclosed string literal
  public static final String BUILTBY = "@DESKTOP-KN14QQK
                                       ^
.\build\generated\src\dev\flang\tools\Version.java:69: error: unclosed string literal
  ";
  ^
4 errors
make: *** [Makefile:316: build/classes/dev/flang/tools/__marker_for_make__] Error 1

**Comment by michaellilltokiwa** [comment]
@Ivo-Balbaert okay thanks. can you do a 'make clean' before 'make'?

**Comment by Ivo-Balbaert** [comment]
Thank you - make completed successfully after a make clean.
